### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Gregeg** [Gregeg/Bezier-Curves-Processing#8]
What should we name the program?
 Autoscout? Pursuit planner? 578’s Autonomous Pathmaker? Stuzzy’s scouter?

@wmortimer64 let me know if you have any ideas or like a name or something

**Comment by wmortimer64** [comment]
the gurg guider?

**Comment by Gregeg** [comment]
ooo, yea that ones good!

**Comment by Gregeg** [comment]
don't really want it named after me though
I still prefer stuzzy's scouter
